### ISSUE TITLE
sticky element keep fixed, if there's no height for the parent element

### ISSUE THREAD

**Issue by wobe** [leafo/sticky-kit#101]
hey! my problem is that if i dont set a px height for the parent element in the css (because it depends on the flexible content in it), the sticky element will remain fixed as i scroll through the parent element. is there a way to fix it?

**Comment by leafo** [comment]
The problem most likely is that the height of the parent element is changing as the page loads. The most recent version has some code to attempt to detect it but it's not perfect. I suggest triggering recalc when the page is done loading.

See the section on recalc: http://leafo.net/sticky-kit/#reference
