### ISSUE TITLE
Is it possible to use "transform:translateY" instead of "top"?

### ISSUE THREAD

**Issue by margox** [leafo/sticky-kit#104]
I think it will be more smooth when the sidebar moving up/down. :)

**Comment by marfnk** [comment]
Due to this article it is not generally true:
http://blog.tumult.com/2013/02/28/transform-translate-vs-top-left/
If you want to use transform, just change line 15:
from `top: offset` to `transform: "translateY(" + offset + ")",`

**Comment by margox** [comment]
In that case , "top" is a better choice indeed, thank you so much :)
