### ISSUE TITLE
Disable on mobile (lower resolutions)

### ISSUE THREAD

**Issue by Anydog** [leafo/sticky-kit#106]
Hi,
I tried to make sticky kit disable on lower resolution with (simplified example) :
if( $(document).width() > 1024 ) {
$j("#my-div").stick_in_parent()
}
, but it doesn't seem to work ...
Any ideas ?

**Comment by leafo** [comment]
You'll need to detach it when the browser enters a lower resolution, see the `sticky_kit:detach` event: http://leafo.net/sticky-kit/#reference

**Comment by andreyvolokitin** [comment]
But what needs to be done to attach sticky kit back if screen size increases?

**Comment by andreyvolokitin** [comment]
Okay, maybe we need to just reinit as we do on normal init...
