### ISSUE TITLE
Inner scrolling not working

### ISSUE THREAD

**Issue by Maaark** [leafo/sticky-kit#107]
Hello,

The inner scrolling isn't working. The var delta doesn't have the set value in the
 `if (last_pos != null) {
          delta = scroll - last_pos;
        }`
 part when it's used to calculate the top value. It always return's 0. Can you have a look at this? I have no idea on how to fix it.

**Comment by leafo** [comment]
Were you able to figure out the problem?

**Comment by Maaark** [comment]
{recalc_every: 1} was causing the issue, removed that part and now trigger the recalc only when needed.

**Comment by andreyvolokitin** [comment]
Should not inner scrolling work with ```recalc_every: 1```?
