### ISSUE TITLE
Is there a way to disable it with a jQuery callback or something?

### ISSUE THREAD

**Issue by evanart** [leafo/sticky-kit#109]
So essentially I have it running, but I'd like the user to be able to click a button to disable the sticky sidebar. I can achieve this with some CSS that just overwrites the script's CSS, but it's still running in the background. Is there a way run something like:

$(".stick").unstick_from_parent();

Which would disable the script until I re-enable it?

**Comment by leafo** [comment]
Please read the reference manual: http://leafo.net/sticky-kit/#reference
