### ISSUE TITLE
Need to detach the sticky when on mobile

### ISSUE THREAD

**Issue by archampion** [leafo/sticky-kit#121]
Hi, I'm having an issue when on mobile. Apparently I have 2 sticky elements but on mobile they are covering about 70% of the screen so I need them or at least 1 element to detach the sticky position.

How can I make this happen?

And by the way, what does bottom out do? Placing the sticky element to the bottom?

**Comment by leafo** [comment]
Please see `sticky_kit:detach` the in the documentation: http://leafo.net/sticky-kit/#reference

**Comment by archampion** [comment]
Yes, I know there's sticky_kit:detach. But how should I apply this on mobile?

1 solution I tried is to put position: static !important to the element so sticky_kit:detach is not use.

I'm not sure how this would affect anything. Right now, it seems fine.

Let me know your thoughts. Thanks.

**Comment by leafo** [comment]
You'll need to detect when you're mobile in javascript and call detach/stick_in_parent accordingly.

I can't guarantee the CSS approach will always work, and it might confuse the calculation step, so detaching is the safest way to do it.
