### ISSUE TITLE
Stuck items reloading

### ISSUE THREAD

**Issue by yesiamben** [leafo/sticky-kit#122]
I'm getting reloads on external stuff in the stuck columns - adsense ads, facebook like buttons etc. Doesn't happen if I'm not loading sticky-kit, does if it loads. Page doesn't reload, and sticky works as it should otherwise.

Had a quick look through the issues and found something similar to this (about embedded PDFs), but it was closed. Has this problem been resolved / is there a fix?

Thanks regardless, Sticky Kit is great :-)

**Comment by leafo** [comment]
When the spacer element is inserted in some scenarios the dom has to be rewritten and this causes some other plugins to choke. Try wrapping your element in an extra div and passing a `spacer` option to sticky kit with a jquery object pointing to that element.

**Comment by yesiamben** [comment]
Perfect! Many thanks!
