### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by igl** [leafo/sticky-kit#131]
Would you consider publishing this on npm?
I don't want to use bower anymore (got burned once by "unable to find suitable version" mess) and i don't like to check this in into source control :)

`npm i --save jquery-sticky-kit` would be lovely.

**Comment by tforssander** [comment]
+1

**Comment by pdlug** [comment]
+1

**Comment by jonscottclark** [comment]
Yup, please add!

**Comment by ryuran** [comment]
+1

**Comment by aaronjpitts** [comment]
+1

**Comment by tedw** [comment]
+1

FYI, you can use https://www.npmjs.com/package/napa to install stuff not published on npm

**Comment by leafo** [comment]
https://www.npmjs.com/package/sticky-kit it's there now, sorry for the delay. This is my first npm package so tell me if I did anything wrong.

**Comment by tedw** [comment]
@leafo Thanks for publishing on npm! Just submitted a pull request to fix a minor typo in the "main" path :wink:

**Comment by unematiii** [comment]
Still not fixed? Should be "main": "dist/sticky-kit.js" instead of "main": "sticky-kit.js"?

**Comment by jonscottclark** [comment]
@unematiii 

merged PR: https://github.com/leafo/sticky-kit/commit/1a7fc21119b4d50fb62829484e58e4a6d07a891d
current file: https://github.com/leafo/sticky-kit/blob/master/package.json#L5

**Comment by igl** [comment]
this fix is probably not in the currently published version on npm

**Comment by jonscottclark** [comment]
@igl hmm, you're right. npm says it's serving 1.1.3 but it's not appearing as a tagged release here. Though it looks like @leafo is doing some work on this again so maybe a release will be in the works? 😄
