### ISSUE TITLE
how add the options

### ISSUE THREAD

**Issue by xavierartot** [leafo/sticky-kit#144]
Hi,
the first one doesn't work, the .care-title works?
```
        $(".our-model-sticky").stick_in_parent({
          'parent': '.our-model',
          'offset_top': '30px'
        });
        $(".care-title").stick_in_parent('.personalized-care');
```
In the website we have to pass the keyword parent?

thanks

**Comment by leafo** [comment]
The second option won't work how you expect, the string will effectively be an empty options set to the `stick_in_parent` function. The first form should work, make sure that `.our-model` exists and wraps the sticky element.
