### ISSUE TITLE
missing example

### ISSUE THREAD

**Issue by serdarkok** [leafo/sticky-kit#148]
Hi leafo;

Your example is missing. I try same things but it's not work. I download zip file open template or example but it's not work. Sorry.

![stickjy](https://cloud.githubusercontent.com/assets/14201646/12239396/32ccedbe-b891-11e5-8264-e72c3067299e.JPG)

You use  "data-sticky_parent" , "data-sticky_column" in div tags, what is this? You don't mention about thats. Why?

Can you make simple, very very simple example and upload anywhere. Your Example and your support is complicated, I am sorry.

Thanks.

**Comment by neb1neuron** [comment]
Try this http://codepen.io/neb1/pen/QyXBBJ
