### ISSUE TITLE
Videos stops & Embed media reload while scrolling

### ISSUE THREAD

**Issue by Serpentsoft** [leafo/sticky-kit#162]
Hi pal,

I discovered an odd issue when the post has any type of videos or Embeded Status like (Tweets and Instagram), so while scrolling and exactly when the function sticky_in_parent triggered videos stopped and embeded status reloaded.

I tried a lot to search and resolve but i had failed, Any idea??

Thanks for your help.

**Comment by leafo** [comment]
https://github.com/leafo/sticky-kit/wiki/Troubleshooting#my-adsiframeplugin-based-content-flashes-or-get-removed-when-it-becomes-sticky
