### ISSUE TITLE
Scrollable Sticky Element doesn't work with recalc_every : 1

### ISSUE THREAD

**Issue by CHEWX** [leafo/sticky-kit#187]
Hi,

Great lib.

As per title really. If you turn the recalc on and off it works differently.

I don't want to use recalc_every, but when it picks up sticky, it's really stuttery for the first 5 - 10px. I can produce a video if you need.

But anyway, would be good to get it working the same regardless of recalc.

Thanks,

**Comment by leafo** [comment]
I'll need to see a stripped down example of the issue happening. Please create a simple html page that demonstrates the issue and I'll look through for the issue.

Closing this for now.
