### ISSUE TITLE
 Uncaught TypeError: $(...).stick_in_parent is not a function

### ISSUE THREAD

**Issue by MagSag** [leafo/sticky-kit#188]
I've included the plugin after my jquery: 

```
<script src="/q/public_html/assets/cf47abfa/jquery.js"></script>
<script src="/q/public_html/assets/58365cb2/qui.js"></script>
<script src="/q/public_html/stickykit.min.js"></script>
```

but when I write :
`$("#side-left").stick_in_parent();`
or
`$("#side-left,#aside-right").stick_in_parent();`
I am getting the error : 

>  Uncaught TypeError: $(...).stick_in_parent is not a function
In the browser console; What I am doing wrong?

**Comment by leafo** [comment]
Maybe you have another jquery instance loaded on the page afterwards that's overwriting all the plugins?

Closing since this isn't an issue with this library.

**Comment by NoLooseEnds** [comment]
I have the same issue.

I've debugged it to have something to do with the build process (i.e minifying and combining of scripts). I use [gulp-starter](https://github.com/vigetlabs/gulp-starter) to build my projects. Never had any problems with other scripts.

I get the error even if I remove all other JS, and just have jquery and sticky-kit. The only workaround I have found is to load it via CDN.

**Comment by shanecarmody** [comment]
I have the same issue:

```
Uncaught TypeError: $advertContainer.find(...).stick_in_parent is not a function
```

**Comment by mommaroodles** [comment]
I have the same error ` Uncaught TypeError: jQuery(...).stick_in_parent is not a function`

**Comment by StarsoftAnalysis** [comment]
I think the problem is that you are using the non-jQuery version of sticky kit 'https://github.com/leafo/sticky-kit/blob/master/dist/sticky-kit.js' from https://github.com/leafo/sticky-kit/tree/master/dist rather than the jQuery version 'https://cdn.rawgit.com/leafo/sticky-kit/v1.1.2/jquery.sticky-kit.js' from http://leafo.net/sticky-kit/.

The documentation isn't clear on the distinction.

**Comment by shiyu99** [comment]
> 
> 
> I think the problem is that you are using the non-jQuery version of sticky kit 'https://github.com/leafo/sticky-kit/blob/master/dist/sticky-kit.js' from https://github.com/leafo/sticky-kit/tree/master/dist rather than the jQuery version 'https://cdn.rawgit.com/leafo/sticky-kit/v1.1.2/jquery.sticky-kit.js' from http://leafo.net/sticky-kit/.
> 
> The documentation isn't clear on the distinction.

Hi, I just ran into the same issue. I found your answer interesting! May I ask how could I use the jQuery version though? I'm using a template program to build a website. I don't know where should I change the code to switch the version of jQuery. Thank you!

**Comment by DJPVMA** [comment]
> > I think the problem is that you are using the non-jQuery version of sticky kit 'https://github.com/leafo/sticky-kit/blob/master/dist/sticky-kit.js' from https://github.com/leafo/sticky-kit/tree/master/dist rather than the jQuery version 'https://cdn.rawgit.com/leafo/sticky-kit/v1.1.2/jquery.sticky-kit.js' from http://leafo.net/sticky-kit/.
> > The documentation isn't clear on the distinction.
> 
> Hi, I just ran into the same issue. I found your answer interesting! May I ask how could I use the jQuery version though? I'm using a template program to build a website. I don't know where should I change the code to switch the version of jQuery. Thank you!

You just download that file, upload it to your server, and then find the code, and change the src="/js/new-stickykit.min.js" in the <script src="/js/stickykit.min.js"></script> code

**Comment by DJPVMA** [comment]
To anyone running into this problem. Did you defer your .js files? If you or someone else did, then make sure to remove any defer or defer="defer" codes from your main jquery <script src= and your sticky <script src=
