### ISSUE TITLE
Performance for long DOM text

### ISSUE THREAD

**Issue by TomThak** [leafo/sticky-kit#191]
Hello,
I have serious problems with performance of the plug in, when there is a really long DOM document.
If I fix like 3elements and I have really long parent with many texts like legislation document, it totaly freezes any browser if I apply the plug in.

**Comment by leafo** [comment]
Performance should be no different than using `position: fixed` as long as you're not telling it to update every scroll frame. Can you show the code you're using to initialize the library?

**Comment by leafo** [comment]
Closing this, open again if you have more information.

For anyone curious about performance, make sure you're not using `recalc_every: 1` since it causes a lot of work to be done in the scroll handler.
