### ISSUE TITLE
[Chrome 56] Infinite looping on "sticky_kit:stick"

### ISSUE THREAD

**Issue by ivelfan** [leafo/sticky-kit#219]
Hello,

In the new version of Chrome, "sticky_kit:stick" event is triggered endlessly.

**Comment by DieterDW** [comment]
I'm having trouble with chrome 56. Several pages keep scrolling down w/o doing something.
Is there a workaround? i noticed 'position: sticky' is back in 56: https://developers.google.com/web/updates/2017/01/nic56

**Comment by heskethw** [comment]
This is fixed by pull request #218

**Comment by DieterDW** [comment]
Awesome, fixed the issue. Thx for the quick response!

**Comment by ivelfan** [comment]
Hope this P.R will merge soon.

**Comment by evanart** [comment]
Any word on when this will get merged? The issue causes the page to scroll on its own while the stick event spams out. It seems to happen the most when Chrome is zoomed out/in, or when Windows has DPI scaling on.

**Comment by cgmajor** [comment]
Would it be possible to get an updated minified JS file with this fix?

**Comment by DieterDW** [comment]
Yeah, the phantom scrolling is gone with this: https://raw.githubusercontent.com/jsit/sticky-kit/669aaa40abb91b8cf693b44a6b23c878c14e5ca6/dist/sticky-kit.js

But it isn't a fix for the script.

**Comment by RenaudParis** [comment]
Thanks @DieterDW it seems to be working fine now! Any idea what BCB happened in Chrome that caused this bug?

**Comment by evanart** [comment]
@RenaudParis I gave @DieterDW 's version a shot and I'm still having an issue with phantom scrolling when the browser is zoomed to 90%.

**Comment by DieterDW** [comment]
@evanart I got it from [#218](https://github.com/leafo/sticky-kit/pull/218)
