### ISSUE TITLE
.outerWidth() rounding can cause issues

### ISSUE THREAD

**Issue by eusonic** [leafo/sticky-kit#42]
It's possible for elements to have fractional widths, e.g. 225.5px. This is very common in percentage based layouts, such as Zurb Foundation's grid system.

jQuery's .width() and .outerWidth() functions will round to the nearest px. When Sticky-Kit creates the spacer div it will use this rounded value, potentially breaking your layout.

Steps to reproduce:
1. Go to http://jsfiddle.net/eusonic/6VL6X/1/
2. Adjust the width of the result panel (lower right) until the divs have fractional widths. This may take a few tries.
3. Try scrolling down. The right column will drop below the sidebar column, because the spacer div is very slightly too wide and there isn't enough room for the main column.

There is an old jQuery bug report for this, but I'm not hopeful it will get fixed anytime soon: http://bugs.jquery.com/ticket/9628

A better solution would be using the native .getBoundingClientRect() method instead of jQuery's .outerWidth(). I think we would then need to add the padding and border, and possibly account for some crossbrowser issues. See http://stackoverflow.com/a/16072668/952156

**Comment by jonscottclark** [comment]
+1 for @eusonic 's suggestion to use `elm[0].getBoundingClientRect().width` instead of `elm.outerWidth(true)`

Changing the source code to use this solved all my issues with percentage-based widths. I'll see what I can do about quickly setting up a pull request to solve this.

**Comment by kaermorchen** [comment]
@leafo I catch this problem with grid Bootstrap 3. Solution proposed @jonscottclark looks good. Are there any fixes?

**Comment by apomili** [comment]
Same problem, the fix is ok, but it would be nice have the fix in the next release

**Comment by Lab43** [comment]
Fixed in https://github.com/leafo/sticky-kit/commit/5e461c1a3e58f1631e66379e28346d341a8bcb8e
