### ISSUE TITLE
Sticks to bottom of container when getting close to bottom

### ISSUE THREAD

**Issue by jakejackson1** [leafo/sticky-kit#81]
Hi,

Great little plugin. This doesn't happen on all pages, but on some there appears to be an issue (tested in the latest versions of Firefox and Chrome) whereby it miscalculate the height and sticks it to the bottom of the container. See screenshot explaining the issue a little more. 

![stickit1](https://cloud.githubusercontent.com/assets/2918419/5023967/5e7924de-6b56-11e4-984b-4b07b9f9d25b.png)

![stickit](https://cloud.githubusercontent.com/assets/2918419/5023943/f8a6744a-6b55-11e4-9019-5a8962b2fcde.png)

**Comment by meharajM** [comment]
How can I prevent recalc from being triggered on window.resize() ?
