### ISSUE TITLE
inner_scrolling doesn't work

### ISSUE THREAD

**Issue by forwardtrends** [leafo/sticky-kit#83]
I have a fluid height sidebar (show / hide elements can expand or contract) - even though I'm recalc'ing throughout the document, and when each show / hide is fired I cannot get it to use the inner_scrolling functionality. The only way a user can see the bottom of the sidebar if it's larger than viewport is if they scroll all the way to the bottom of the screen. Any ideas?

**Comment by leafo** [comment]
Closing this issue until it's updated with example of issue happening https://github.com/leafo/sticky-kit/blob/master/CONTRIBUTING.md
