### ISSUE TITLE
Sticky not being called on elements that are inside of tabs

### ISSUE THREAD

**Issue by katrinkerber** [leafo/sticky-kit#84]
I have sticky elements within tab-like sections, so one section will show on load, the others are hidden until the tab link is clicked.

Only sticky elements that are within the 'open' section on page load will work.

Is there a way to get the these elements to stick as well once they are visible?

**Comment by leafo** [comment]
sticky kit can't calculate the dimensions of things that aren't visible on the page. I suggest hooking in `detach` and `stick_in_parent` as callbacks to the code that hides and shows tabs.

**Comment by patrickdwyer** [comment]
@katrinkerber were you able to figure this out?  I'm facing the same dilemma and cannot resolve.

**Comment by katrinkerber** [comment]
@patrickdwyer This is a long time ago. Just had a quick browse through my code from back then and I don't think I did find a solution...
