### ISSUE TITLE
destroy or disable on mobile

### ISSUE THREAD

**Issue by yonihbc** [leafo/sticky-kit#85]
is there a way to make it disabled on responsive website?

**Comment by andreyvolokitin** [comment]
No reattach though?

**Comment by spyrosvl** [comment]
Here is an example about how to resolve this:

`jQuery(document).ready(function(){


    var window_width = jQuery( window ).width();
    
    if (window_width < 768) {
      jQuery("#sidebar").trigger("sticky_kit:detach");
    } else {
      make_sticky();
    }
  
    jQuery( window ).resize(function() {
      
      window_width = jQuery( window ).width();
      
      if (window_width < 768) {
        jQuery("#sidebar").trigger("sticky_kit:detach");
      } else {
        make_sticky();
      }
      
    });
    
    function make_sticky() {
      jQuery("#sidebar").stick_in_parent({
        parent: '.entry-content'
      });
    }

});`

**Comment by laurelstreng** [comment]
Still can't seem to get `sticky_kit:detach`  to work at all on window resize (with/without conditionals on the window width). Anyone else having trouble with this?

```javascript
$(window).on('resize', function(){
  $(".sticky.menu").trigger("sticky_kit:detach");
});
```

**Comment by alisharait** [comment]
# very nice

**Comment by sasanikolic90** [comment]
Thanks @spyrosvl, that works great.

**Comment by navedkhan012** [comment]
/*=====================
	     sticky 
=====================*/
 $(window).load(function(){
$("#sidebar").stick_in_parent({
	offset_top: 20,
});
    var window_width = jQuery( window ).width();
    if (window_width < 768) {
      jQuery("#sidebar").trigger("sticky_kit:detach");
    } else {
      make_sticky();
    }
    jQuery( window ).resize(function() {
      window_width = jQuery( window ).width();
      if (window_width < 768) {
        jQuery("#sidebar").trigger("sticky_kit:detach");
      } else {
        make_sticky();
      }
    });
    function make_sticky() {
      jQuery("#sidebar").stick_in_parent({
        parent: '.entry-content'
      });
    }
});

**Comment by fatmarker** [comment]
Thanks for sharing this.
