### ISSUE TITLE
Sticky element (side content) moves below non-sticky element (main content) at larger screen widths.

### ISSUE THREAD

**Issue by clampdesign** [leafo/sticky-kit#89]
On smaller width screens (below around 1000px) it works as intended. However, on larger width screens, the sidebar (sticky element) stops scrolling as intended, but as soon as you get to the bottom of the main content, it moves underneath (still on the right side). There are no media queries in the code that should change anything at larger widths. See <a href="http://jsfiddle.net/64gqmk5m/7/">this fiddle</a>. I had to shift the javascript box to make the result box large enough to see the problem.

**Comment by mintyPT** [comment]
I'm using the plugin to do a top menu but I have the same issue. Did you happen to fix this by now? I know it's only been 4 days :)

**Comment by clampdesign** [comment]
No, unfortunately I'm not sure where to start to fix this issue. I am hoping to hear from the developer.  Your issue is also only on larger width screens?

**Comment by leafo** [comment]
looks like a rounding issue, 33.3% is converted to pixel amount to make the spacer, but it's probably 1 pixel more than the width of the available area.

**Comment by mintyPT** [comment]
Actually I solved my issue already. I used this: https://github.com/leafo/sticky-kit/issues/31#issuecomment-51740033 

Hope it helps.

**Comment by clampdesign** [comment]
Thank you, leafo! It was, in fact, a rounding error. I've changed my sidebar to 33.32% and voila. Fixed.

**Comment by web2style** [comment]
@leafo You don't have to use rounded values for width, because it's impossible to use the plugin with percentage-width columns, as in bootstrap. The plugin always use wider values and the layout breaks.
