### ISSUE TITLE
possible to set height in fixed mode to be different?

### ISSUE THREAD

**Issue by gebrits** [leafo/sticky-kit#95]
Say I've got a tall toolbar, of which I only want to make the bottom part sticky. Is this possible using sticky-kit? 

As an example please see the [fixed appbar]( http://www.google.com/design/spec/material-design/introduction.html#) from Google Material Design for instance.

**Comment by leafo** [comment]
Sure, there are a bunch of ways to do tihs. The easiest would probably be to make the actual sticky element invisible to begin with and have it appear when it becomes stuck.
